### ISSUE TITLE
Switch to Front camera but Failed.

### ISSUE THREAD

**Issue by ZhuFengdaaa** [chatea/ServiceCamera#1]
[Stackoverflow Post here](http://stackoverflow.com/questions/29177932/front-camera-record-video-failed?noredirect=1#comment46576918_29177932)

I just change 2 Lines of the project to switch to the front camera but it failed.  Under the path it generate a MP4 file, but my cell phone failed to open it.  _(real device debugging)_

**Comment by ZhuFengdaaa** [comment]
By changing `mMediaRecorder.setProfile(CamcorderProfile.get(1,CamcorderProfile.QUALITY_HIGH));` ==> `mMediaRecorder.setProfile(CamcorderProfile.get(1,CamcorderProfile.QUALITY_LOW));`
it works well, but I don't know why?
[My answer](http://stackoverflow.com/a/29184195/4388898)

**Comment by chartsai** [comment]
I think your front camera doesn't support the highest quality. You can use `CamcorderProfile.hasProfile(int cameraId, int quality)` to check if the quality is supported by specified camera. See http://developer.android.com/reference/android/media/CamcorderProfile.html
