### ISSUE TITLE
After selecting the front camera, recording is performed by the Back camera

### ISSUE THREAD

**Issue by sdroider** [chatea/ServiceCamera#12]
After selecting the front camera, recording is performed by the Back camera:

`mMediaRecorder.setProfile(CamcorderProfile.get(findFrontFacingCamera(),CamcorderProfile.QUALITY_LOW));`

```
private int findFrontFacingCamera() {
        int cameraId = -1;
        // Search for the front facing camera
        int numberOfCameras = Camera.getNumberOfCameras();
        for (int i = 0; i < numberOfCameras; i++) {
            Camera.CameraInfo info = new Camera.CameraInfo();
            Camera.getCameraInfo(i, info);
            if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
                Log.d(TAG, "Camera found");
                cameraId = i;
                break;
            }
        }
        return cameraId;
    }
```

What am I doing wrong?Help me please

**Comment by chartsai** [comment]
Your code is correct.
The issue is caused by  `mMediaRecorder.setProfile(CamcorderProfile.get(CamcorderProfile.QUALITY_HIGH));` since the front camera doesn't support high quality video recording.

The new commit fixed the problem.

**Comment by sdroider** [comment]
Hello Charlie. You misunderstood my question. I do not use high quality. I
use low quality. Look carefully at my code. I want to get a low quality
recording from the front camera. But the recording is done by the back
camera. I want to record a front-facing camera. You understand me???)
28 мар 2017 г. 1:43 AM пользователь "Charlie Tsai" <notifications@github.com>
написал:

**Comment by chartsai** [comment]
Maybe you didn't use the correct camera id? You didn't post all of your code so I cannot debug with it. Check the new changes which can record video from front camera.

**Comment by sdroider** [comment]
Okay friend! I'm sending you a java-file of my class. Tell me what I'm
doing wrong?

2017-03-28 7:36 GMT+04:00 Charlie Tsai <notifications@github.com>:

**Comment by sdroider** [comment]
`
package example.chatea.servicecamera;

import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.graphics.PixelFormat;
import android.hardware.Camera;
import android.media.CamcorderProfile;
import android.media.MediaRecorder;
import android.os.Bundle;
import android.os.IBinder;
import android.os.ResultReceiver;
import android.util.Log;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.WindowManager;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;

public class CameraService extends Service {
    private static final String TAG = "myLog";

    public static final String RESULT_RECEIVER = "resultReceiver";
    public static final String VIDEO_PATH = "recordedVideoPath";

    public static final int RECORD_RESULT_OK = 0;
    public static final int RECORD_RESULT_DEVICE_NO_CAMERA= 1;
    public static final int RECORD_RESULT_GET_CAMERA_FAILED = 2;
    public static final int RECORD_RESULT_ALREADY_RECORDING = 3;
    public static final int RECORD_RESULT_NOT_RECORDING = 4;

    private static final String START_SERVICE_COMMAND = "startServiceCommands";
    private static final int COMMAND_NONE = -1;
    private static final int COMMAND_START_RECORDING = 0;
    private static final int COMMAND_STOP_RECORDING = 1;

    private Camera mCamera;
    private MediaRecorder mMediaRecorder;

    private boolean mRecording = false;
    private String mRecordingPath = null;

    public CameraService() {
    }

    public static void startToStartRecording(Context context, ResultReceiver resultReceiver) {
        Intent intent = new Intent(context, CameraService.class);
        intent.putExtra(START_SERVICE_COMMAND, COMMAND_START_RECORDING);
        intent.putExtra(RESULT_RECEIVER, resultReceiver);
        context.startService(intent);
    }

    public static void startToStopRecording(Context context, ResultReceiver resultReceiver) {
        Intent intent = new Intent(context, CameraService.class);
        intent.putExtra(START_SERVICE_COMMAND, COMMAND_STOP_RECORDING);
        intent.putExtra(RESULT_RECEIVER, resultReceiver);
        context.startService(intent);
    }

    /**
     * Used to take picture.
     */
    private Camera.PictureCallback mPicture = new Camera.PictureCallback() {
        @Override
        public void onPictureTaken(byte[] data, Camera camera) {
            File pictureFile = Util.getOutputMediaFile(Util.MEDIA_TYPE_IMAGE);

            if (pictureFile == null) {
                return;
            }

            try {
                FileOutputStream fos = new FileOutputStream(pictureFile);
                fos.write(data);
                fos.close();
            } catch (FileNotFoundException e) {
            } catch (IOException e) {
            }
        }
    };

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        switch (intent.getIntExtra(START_SERVICE_COMMAND, COMMAND_NONE)) {
            case COMMAND_START_RECORDING:
                handleStartRecordingCommand(intent);
                break;
            case COMMAND_STOP_RECORDING:
                handleStopRecordingCommand(intent);
                break;
            default:
                throw new UnsupportedOperationException("Cannot start service with illegal commands");
        }

        return START_STICKY;
    }

    private void handleStartRecordingCommand(Intent intent) {
        final ResultReceiver resultReceiver = intent.getParcelableExtra(RESULT_RECEIVER);

        if (mRecording) {
            // Already recording
            resultReceiver.send(RECORD_RESULT_ALREADY_RECORDING, null);
            return;
        }
        mRecording = true;

        if (Util.checkCameraHardware(this)) {
            mCamera = Util.getCameraInstance();
            if (mCamera != null) {
                SurfaceView sv = new SurfaceView(this);

                WindowManager wm = (WindowManager) getSystemService(Context.WINDOW_SERVICE);
                WindowManager.LayoutParams params = new WindowManager.LayoutParams(1, 1,
                        WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY,
                        WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH,
                        PixelFormat.TRANSLUCENT);

                SurfaceHolder sh = sv.getHolder();

                sv.setZOrderOnTop(true);
                sh.setFormat(PixelFormat.TRANSPARENT);

                sh.addCallback(new SurfaceHolder.Callback() {
                    @Override
                    public void surfaceCreated(SurfaceHolder holder) {
                        Camera.Parameters params = mCamera.getParameters();
                        mCamera.setParameters(params);
                        Camera.Parameters p = mCamera.getParameters();

                        List<Camera.Size> listSize;

                        listSize = p.getSupportedPreviewSizes();
                        Camera.Size mPreviewSize = listSize.get(2);
                        Log.v("TAG", "preview width = " + mPreviewSize.width
                                + " preview height = " + mPreviewSize.height);
                        p.setPreviewSize(mPreviewSize.width, mPreviewSize.height);

                        listSize = p.getSupportedPictureSizes();
                        Camera.Size mPictureSize = listSize.get(2);
                        Log.v("TAG", "capture width = " + mPictureSize.width
                                + " capture height = " + mPictureSize.height);
                        p.setPictureSize(mPictureSize.width, mPictureSize.height);
                        mCamera.setParameters(p);

                        try {
                            mCamera.setPreviewDisplay(holder);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        mCamera.startPreview();

                        mCamera.unlock();

                        mMediaRecorder = new MediaRecorder();
                        mMediaRecorder.setCamera(mCamera);

                        mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
                        mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.CAMERA);
                        mMediaRecorder.setProfile(CamcorderProfile.get(findFrontFacingCamera(),CamcorderProfile.QUALITY_LOW));

                        mRecordingPath = Util.getOutputMediaFile(Util.MEDIA_TYPE_VIDEO).getPath();
                        mMediaRecorder.setOutputFile(mRecordingPath);

                        mMediaRecorder.setPreviewDisplay(holder.getSurface());

                        try {
                            mMediaRecorder.prepare();
                        } catch (IllegalStateException e) {
                            Log.d(TAG, "IllegalStateException when preparing MediaRecorder: " + e.getMessage());
                        } catch (IOException e) {
                            Log.d(TAG, "IOException when preparing MediaRecorder: " + e.getMessage());
                        }
                        mMediaRecorder.start();

                        resultReceiver.send(RECORD_RESULT_OK, null);
                        Log.d(TAG, "Recording is started");
                    }

                    @Override
                    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                    }

                    @Override
                    public void surfaceDestroyed(SurfaceHolder holder) {
                    }
                });


                wm.addView(sv, params);

            } else {
                Log.d(TAG, "Get Camera from service failed");
                resultReceiver.send(RECORD_RESULT_GET_CAMERA_FAILED, null);
            }
        } else {
            Log.d(TAG, "There is no camera hardware on device.");
            resultReceiver.send(RECORD_RESULT_DEVICE_NO_CAMERA, null);
        }
    }

    private int findFrontFacingCamera() {
        int cameraId = -1;
        // Search for the front facing camera
        int numberOfCameras = Camera.getNumberOfCameras();
        for (int i = 0; i < numberOfCameras; i++) {
            Camera.CameraInfo info = new Camera.CameraInfo();
            Camera.getCameraInfo(i, info);
            if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
                Log.d(TAG, "Camera found");
                cameraId = i;
                break;
            }
        }
        return cameraId;
    }


    private void handleStopRecordingCommand(Intent intent) {
        ResultReceiver resultReceiver = intent.getParcelableExtra(RESULT_RECEIVER);

        if (!mRecording) {
            // have not recorded
            resultReceiver.send(RECORD_RESULT_NOT_RECORDING, null);
            return;
        }

        mMediaRecorder.stop();
        mMediaRecorder.release();
        mCamera.stopPreview();
        mCamera.release();

        Bundle b = new Bundle();
        b.putString(VIDEO_PATH, mRecordingPath);

        mRecordingPath = null;

        resultReceiver.send(RECORD_RESULT_OK, b);

        mRecording = false;
        Log.d(TAG, "recording is finished.");
    }

    @Override
    public IBinder onBind(Intent intent) {
        // TODO: Return the communication channel to the service.
        throw new UnsupportedOperationException("Not yet implemented");
    }
}`

**Comment by chartsai** [comment]
Hi,

For the line here:
`        mCamera = Util.getCameraInstance();`

Did you modify the `Util.getCameraInstance()` function to get the front camera?

**Comment by sdroider** [comment]
Oh! Friend! Thank you! I modified this method for the front camera. Now everything works! 

2017-03-28 14:53 GMT+04:00 Charlie Tsai <notifications@github.com>:

**Comment by chartsai** [comment]
Just remove [`mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);`](https://github.com/chartsai/ServiceCamera/blob/master/app/src/main/java/example/chatea/servicecamera/CameraService.java#L172) in [CameraService.java](https://github.com/chartsai/ServiceCamera/blob/master/app/src/main/java/example/chatea/servicecamera/CameraService.java).

**Comment by sdroider** [comment]
I deleted this method. Now the application crashes.

FATAL EXCEPTION: main

       Process: example.chatea.servicecamera, PID: 15568

       java.lang.RuntimeException: Unable to start service
example.chatea.servicecamera.CameraService@e8912c4 with null:
java.lang.NullPointerException: Attempt to invoke virtual method 'int
android.content.Intent.getIntExtra(java.lang.String, int)' on a null
object reference

           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3057)

           at android.app.ActivityThread.access$2200(ActivityThread.java:165)

           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)

           at android.os.Handler.dispatchMessage(Handler.java:102)

           at android.os.Looper.loop(Looper.java:150)

           at android.app.ActivityThread.main(ActivityThread.java:5546)

           at java.lang.reflect.Method.invoke(Native Method)

           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)

           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

        Caused by: java.lang.NullPointerException: Attempt to invoke
virtual method 'int
android.content.Intent.getIntExtra(java.lang.String, int)' on a null
object reference

           at example.chatea.servicecamera.CameraService.onStartCommand(CameraService.java:89)

           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3040)

           at android.app.ActivityThread.access$2200(ActivityThread.java:165)

           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)

           at android.os.Handler.dispatchMessage(Handler.java:102)

           at android.os.Looper.loop(Looper.java:150)

           at android.app.ActivityThread.main(ActivityThread.java:5546)

           at java.lang.reflect.Method.invoke(Native Method)

           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)

           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)


2017-03-29 18:42 GMT+04:00 Charlie Tsai <notifications@github.com>:

**Comment by chartsai** [comment]
This is another issue...
Well, I have submitted a change for it.

**Comment by sdroider** [comment]
Will you help me solve this problem?

2017-03-29 20:43 GMT+04:00 Charlie Tsai <notifications@github.com>:
